# import numpy

In [3]:
import numpy as np

In [5]:
arr = np.array([1, 2, 3, 4, 5])
print (arr)

[1 2 3 4 5]


In [8]:
print(type(arr))

<class 'numpy.ndarray'>


# Create a NumPy ndarray Object
NumPy is used to work with arrays. The array object in NumPy is called ndarray.

We can create a NumPy ndarray object by using the array() function.

# Dimentions in array 

# 0D array/ scalers....... Every single value in an array is called 0D.

In [9]:
arr = np.array(42)
print (arr)

42


# 1D and unidimentional array

In [10]:
arr = np.array([11, 22, 33, 433, 533])

print(arr)

[ 11  22  33 433 533]


# 2D array

In [11]:
arr = np.array([[1, 23, 32], [41, 5, 62]])

print(arr)

[[ 1 23 32]
 [41  5 62]]


# 3D array

In [16]:
arr=np.array([[[3,4,5], [22,33,44],[2,7,9]]])
print(arr)

[[[ 3  4  5]
  [22 33 44]
  [ 2  7  9]]]


# number of dimentions.... ndim attribute

In [17]:
a = np.array(42)
b=np.array([11, 22, 33, 433, 533])
c=np.array([[1, 23, 32], [41, 5, 62]])
d=np.array([[[3,4,5], [22,33,44],[2,7,9]]])
print(a.ndim)
print(b.ndim)
print(c.ndim)
print(d.ndim)



0
1
2
3


# Accessing array elements ....... start with 0 index

In [19]:
arr = np.array([1, 2, 3, 4])

print(arr[1])
print(arr[1]+[2])

2
[4]


In [20]:
arr.size

4

# shape and size

In [21]:
#id=vector
#2d=matrix
#3d=cube
#n dimentional =.........
arr.shape                     # 4 elements
                     #vector.. no concept of rows and columns 


(4,)

# creating array  1D, 2D

In [28]:
list (range(10))

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [29]:
arr=np.arange(10)
arr                              # output in the form of tuple and list

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [33]:
arr2d = np.array([[1,2,3] ,[11,22,33],[111,222,333]])    
arr2d

array([[  1,   2,   3],
       [ 11,  22,  33],
       [111, 222, 333]])

In [34]:
arr2d.shape          # 3rows 3 column 


(3, 3)

# Reshape 1d t0 2d or 3d

In [70]:
#arr2d=np.arange(20).reshape(1,20)
arr2d=np.arange(20).reshape(4,5)               # folding or molding 1D TO 2D
#arr2d=np.arange(20).reshape(10,2)             # 20 ke multiples (20,1), (5,4)
(arr2d)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [43]:
arr2d.shape


(4, 5)

In [44]:
arr2d.ndim

2

In [73]:
arr2d.ravel()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [72]:
arr2d.flatten()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [71]:
arr2d.reshape(20)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

# check dimention

In [80]:
arr2d = np.array([10])
arr2d

array([10])

In [81]:
arr2d = np.array([[[[[[[[10]]]]]]]])
arr2d


array([[[[[[[[10]]]]]]]])

In [82]:
arr2d.ndim                 #8 brackets means 8 dimention

8

In [83]:
# 1D
arr = np.array([10])
arr

array([10])

In [84]:
# 2D
arr = np.array([[10]])
arr

array([[10]])

In [107]:
# 3D
arr3d = np.arange(64). reshape(4,4,4)      # depth or no of matrix, rows, columns
arr3d

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11],
        [12, 13, 14, 15]],

       [[16, 17, 18, 19],
        [20, 21, 22, 23],
        [24, 25, 26, 27],
        [28, 29, 30, 31]],

       [[32, 33, 34, 35],
        [36, 37, 38, 39],
        [40, 41, 42, 43],
        [44, 45, 46, 47]],

       [[48, 49, 50, 51],
        [52, 53, 54, 55],
        [56, 57, 58, 59],
        [60, 61, 62, 63]]])

# indexing

In [115]:
arr2d = np.array([[1,2,3] ,[11,22,33]])    
arr2d

array([[ 1,  2,  3],
       [11, 22, 33]])

In [112]:
arr3d[1,3]

array([28, 29, 30, 31])

In [117]:
arr2d[1,2]             #0 row, 1 row
                       # move 2nd value in 1 row .... index number starting from zero

33

In [118]:
arr2d[1][2]

33

In [119]:
arr3d[2,1,3]         #2 matrix no start from 0 matrix index        
                     #1 ROW start from 0 index
                     #3 column 


39

# multiplication

In [130]:
arr=np.arange(10)
arr 

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [138]:
z=[]
for n in arr:
    z.append(n*2)
z

[0, 2, 4, 6, 8, 10, 12, 14, 16, 18]

# Addition...... but same dimentions

In [139]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [144]:
a=np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [145]:
arr+a

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [151]:
# mirroring = element wise operation
a= np.arange(25).reshape(5,5) 
b= np.arange(25,50).reshape(5,5) 

In [152]:
a


array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [153]:
b

array([[25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34],
       [35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44],
       [45, 46, 47, 48, 49]])

# mirror and element wise 

In [154]:
a*b

array([[   0,   26,   54,   84,  116],
       [ 150,  186,  224,  264,  306],
       [ 350,  396,  444,  494,  546],
       [ 600,  656,  714,  774,  836],
       [ 900,  966, 1034, 1104, 1176]])

# linear algebra 

In [159]:
# (5,5) and (5,4)               1column = 2row
a@b            
#a.dot(b)

array([[ 400,  410,  420,  430,  440],
       [1275, 1310, 1345, 1380, 1415],
       [2150, 2210, 2270, 2330, 2390],
       [3025, 3110, 3195, 3280, 3365],
       [3900, 4010, 4120, 4230, 4340]])

# array slicing 

In [160]:
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [161]:
 a[2,3]            # 2 row 3 column    # in indexing get spcific value 

13

In [162]:
type (a[2,3])              

numpy.int32

# for slicing we get values according to dimentions like 2d and 3d 

In [ ]:
# [row   :  column ]
  # [start:end , start:end]

In [163]:
a[2:3 , 3:4]             #here indexing start from 0  
                          # end = n=n-1 for indexing 
                           # indexing and slicing main difference dimensions 

array([[13]])

In [165]:
a[1:4,3]                    # select ist 1---3 rows
                               # aik value ki waja se slicing bn gea 

array([ 8, 13, 18])

In [166]:
a[1:4 , 1:4]

array([[ 6,  7,  8],
       [11, 12, 13],
       [16, 17, 18]])

In [167]:
a[1:4 , 3:4]

array([[ 8],
       [13],
       [18]])

In [168]:
a[4, :4]                          # 1 dimension mn aye gi humesha 
                                  # because start or end ni dea dono mn 
                                 # 0 consider here if we write nothing 

array([20, 21, 22, 23])

# querring array 

In [169]:
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [175]:
mask = a>5    
mask                              #mask 

array([[False, False, False, False, False],
       [False,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True]])

In [176]:
a[mask]                     #show onlyyy true values 

array([ 6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22,
       23, 24])

In [179]:
a[a>5] = 100
a

array([[  0,   1,   2,   3,   4],
       [  5, 100, 100, 100, 100],
       [100, 100, 100, 100, 100],
       [100, 100, 100, 100, 100],
       [100, 100, 100, 100, 100]])

In [180]:
np. where (a>7, 0, a)              # a>7 put 0 otherwise no chng

array([[0, 1, 2, 3, 4],
       [5, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])

In [193]:
a[(a%2==0) & (a%7==0)]                          # and 

array([0])

In [194]:
a[(a%2==0) | (a%7==0)]

array([  0,   2,   4, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100,
       100, 100, 100, 100, 100, 100, 100, 100, 100])

In [196]:
np.where((a%2==0) | (a%7==0), "wow", "ohh")           #unicode data type

array([['wow', 'ohh', 'wow', 'ohh', 'wow'],
       ['ohh', 'wow', 'wow', 'wow', 'wow'],
       ['wow', 'wow', 'wow', 'wow', 'wow'],
       ['wow', 'wow', 'wow', 'wow', 'wow'],
       ['wow', 'wow', 'wow', 'wow', 'wow']], dtype='<U3')

# combining arrays    for joining 

In [200]:
print(a)
a.shape

[[  0   1   2   3   4]
 [  5 100 100 100 100]
 [100 100 100 100 100]
 [100 100 100 100 100]
 [100 100 100 100 100]]


(5, 5)

In [201]:
print(b)
b.shape

[[25 26 27 28 29]
 [30 31 32 33 34]
 [35 36 37 38 39]
 [40 41 42 43 44]
 [45 46 47 48 49]]


(5, 5)

In [202]:
np.concatenate((a,b), axis=0)          # for verticle axis=0

array([[  0,   1,   2,   3,   4],
       [  5, 100, 100, 100, 100],
       [100, 100, 100, 100, 100],
       [100, 100, 100, 100, 100],
       [100, 100, 100, 100, 100],
       [ 25,  26,  27,  28,  29],
       [ 30,  31,  32,  33,  34],
       [ 35,  36,  37,  38,  39],
       [ 40,  41,  42,  43,  44],
       [ 45,  46,  47,  48,  49]])

In [203]:
np.concatenate((a,b), axis=1)          # for horizontal axis=1 

array([[  0,   1,   2,   3,   4,  25,  26,  27,  28,  29],
       [  5, 100, 100, 100, 100,  30,  31,  32,  33,  34],
       [100, 100, 100, 100, 100,  35,  36,  37,  38,  39],
       [100, 100, 100, 100, 100,  40,  41,  42,  43,  44],
       [100, 100, 100, 100, 100,  45,  46,  47,  48,  49]])

In [204]:
np.stack((a,b), axis=0)                            # stack is used for combining but separat each other 
                                                    #axis =0 by default

array([[[  0,   1,   2,   3,   4],
        [  5, 100, 100, 100, 100],
        [100, 100, 100, 100, 100],
        [100, 100, 100, 100, 100],
        [100, 100, 100, 100, 100]],

       [[ 25,  26,  27,  28,  29],
        [ 30,  31,  32,  33,  34],
        [ 35,  36,  37,  38,  39],
        [ 40,  41,  42,  43,  44],
        [ 45,  46,  47,  48,  49]]])

In [206]:
np.vstack((a,b))               # v stack for combing 

array([[  0,   1,   2,   3,   4],
       [  5, 100, 100, 100, 100],
       [100, 100, 100, 100, 100],
       [100, 100, 100, 100, 100],
       [100, 100, 100, 100, 100],
       [ 25,  26,  27,  28,  29],
       [ 30,  31,  32,  33,  34],
       [ 35,  36,  37,  38,  39],
       [ 40,  41,  42,  43,  44],
       [ 45,  46,  47,  48,  49]])