# Convert a 1D array to a 2D array with 2 rows?

In [1]:
import numpy as np

In [2]:
arr1d=np.array([0,1,2,3,4,5,6,7,8,9])
arr2d= np.reshape(arr1d, (2,-1))
arr2d

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

# How to stack two arrays vertically?

In [3]:
a=np.array([[0, 1, 2, 3, 4],
          [5, 6, 7, 8, 9]])


In [4]:
b= np.array([[1, 1, 1, 1, 1],
            [1, 1, 1, 1, 1]])
c=np.vstack((a,b))
print(c)

[[0 1 2 3 4]
 [5 6 7 8 9]
 [1 1 1 1 1]
 [1 1 1 1 1]]


# How to stack two arrays horizontally?

In [8]:
c=np.hstack((a,b))
c

array([[0, 1, 2, 3, 4, 1, 1, 1, 1, 1],
       [5, 6, 7, 8, 9, 1, 1, 1, 1, 1]])

# How to convert an array of arrays into a flat 1d array?

In [9]:
a=np.array([[0,1,2,3,4],[5,6,7,8,9]])
result=np.concatenate(a).flatten()
print(result)



[0 1 2 3 4 5 6 7 8 9]


# How to Convert higher dimension into one dimension?

In [7]:
arr2d=np.array([[0,1,2,3,4],[5,6,7,8,9],[10,11,12,13,14]])
arr1d=arr2d.flatten()
arr1d=arr2d.ravel()
arr1d

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [10]:
arr1d=np.arange(15).reshape(5,3)
print(arr1d)

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]
 [12 13 14]]


# Create 5x5 an array and find the square of an array?

In [12]:
arr1d=np.arange(25).reshape(5,5)
a=np.square(arr1d)
print(a)

[[  0   1   4   9  16]
 [ 25  36  49  64  81]
 [100 121 144 169 196]
 [225 256 289 324 361]
 [400 441 484 529 576]]


# Create 5x6 an array and find the mean?

In [13]:
arr1d=np.arange(30).reshape(5,6)
a=np.mean(arr1d)
print(a)

14.5


# Find the standard deviation of the previous array in Q8?

In [14]:
arr1d=np.arange(30).reshape(5,6)
a=np.std(arr1d)
print(a)

8.65544144839919


# Find the median of the previous array in Q8?

In [15]:
arr1d=np.arange(30).reshape(5,6)
a=np.mean(arr1d)
print(a)

14.5


# Find the transpose of the previous array in Q8?

In [16]:
arr1d=np.arange(30).reshape(5,6)
a=np.transpose(arr1d)
print(a)

[[ 0  6 12 18 24]
 [ 1  7 13 19 25]
 [ 2  8 14 20 26]
 [ 3  9 15 21 27]
 [ 4 10 16 22 28]
 [ 5 11 17 23 29]]


# Create a 4x4 an array and find the sum of diagonal elements?

In [24]:
arr2d=np.array([[0,1,2,3],[4,5,6,7],[8,10,11,12],[13,14,15,16]])
a=np.sum(arr2d.diagonal())
print(a)

32


# Find the determinant of the previous array in Q12?

In [26]:
arr2d=np.array([[2,1,2,3],[4,5,6,7],[8,10,11,12],[13,14,15,16]])
a=np.linalg.det(arr2d)
print(a)

1.665334536937729e-16


# Find the 5th and 95th percentile of an array?

In [28]:
arr2d=np.array([[2,1,2,3],[4,5,6,7],[8,10,11,12],[13,14,15,16]])
a=np.percentile(arr2d,5)
b=np.percentile(arr2d,95)
print(a)
print(b)

1.75
15.25


# How to find if a given array has any null values?